apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "9002"
    spec:
      volumes:
        - name: order-config-volume
          configMap:
            name: order-config
      containers:
        - name: order-service
          image: order-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 5"]
          ports:
            - containerPort: 9002
#          env:
#            - name: CATALOG_SERVICE_URL
#              value: http://catalog-service
#            - name: SPRING_CLOUD_CONFIG_URI
#              value: http://config-service
#            - name: SPRING_R2DBC_URL
#              value: "r2dbc:postgres://polar-postgres/polardb_order"
#            - name: SPRING_FLYWAY_URL
#              value: "jdbc:postgres://polar-postgres/polardb_order"
#            - name: SPRING_RABBITMQ_HOST
#              value: polar-rabbitmq
#            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
#              value: http://polar-keycloak/realms/PolarBookshop
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9002
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9002
            initialDelaySeconds: 5
            periodSeconds: 15
          volumeMounts:
            - name: order-config-volume
              mountPath: /workspace/config
